title: wjplayer
description: Video.js HLS bundle that supports VAST/VMAP ads, 360-degree videos, and more
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
